name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
          - elixir: 1.11.2
            erlang: 23.1
          - elixir: 1.10.2
            erlang: 22.3
          - elixir: 1.9.1
            erlang: 22.3
          - elixir: 1.8.1
            erlang: 21.1
          - elixir: 1.7.4
            erlang: 21.1

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
        otp-version: ${{matrix.erlang}} # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Build Dependencies
      run: mix deps.compile
    - name: Compile
      run: mix compile --warnings-as-errors
    - name: Check format
      run: mix format --check-formatted
    - name: Credo
      run: mix credo --strict
    - name: Run Tests
      run: mix test
